#
# integration
#
# https://github.com/excalibur/integration
#

# Pull base image.
FROM excalibur/integration

MAINTAINER lzy7750015@gmail.com

# config redis

# config mysql

# config tomcat

# config nginx.

ADD ./start.sh /start.sh
RUN chmod 755 /start.sh

CMD /start.sh